# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "comments", :force => true do |t|
    t.column "body",          :text
    t.column "rating",        :integer
    t.column "version",       :string
    t.column "stylesheet_id", :integer
    t.column "user_id",       :integer
    t.column "created_at",    :datetime
  end

  create_table "resources", :force => true do |t|
    t.column "data",          :binary
    t.column "name",          :string
    t.column "mimeType",      :string
    t.column "stylesheet_id", :integer
    t.column "updated_at",    :datetime
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "stylesheets", :force => true do |t|
    t.column "name",               :string
    t.column "description",        :string
    t.column "version",            :string,   :default => "1.0"
    t.column "user_id",            :integer
    t.column "created_at",         :datetime
    t.column "version_updated_at", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "openid_url",     :string
    t.column "nickname",       :string
    t.column "fullname",       :string
    t.column "uses_full_name", :boolean, :default => false
    t.column "homepage",       :string
  end

end
